FROM ubuntu:25.10

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    iputils-ping \
    pkg-config \
    python3-dev \
    python3-numpy \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-libav \
    vim \
    v4l-utils \
    usbutils \ 
    tftp-hpa \
    libavcodec-dev \
    libavformat-dev \
    libavutil-dev \
    libswscale-dev \
    libx264-dev \
    libxvidcore-dev \ 
    libgstreamer1.0-dev \
    libgstreamer-plugins-base1.0-dev 

WORKDIR /Repos/gtcclient
COPY ./utils .

WORKDIR /Repos



# COPY ../GTClash .
